[package]
name = "wetyu-desktop"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
opt-level = 3

[dependencies]
cpal = "=0.18.2"
eframe = { version = "=0.36.2", default-features = false, features = ["glow", "default_fonts"] }
rtrb = "=0.4.0"
wetyu = { version = "0.1.0", path = "../wetyu" }
